feat: move non-subcircuit group
tscircuit/core pull request #431
Opened 2024-12-17 20:09 UTC by imrishabh18

/close #390

2024-12-17 20:15 UTC, seveibar reviewed
Not a bad implementation but i have a slightly different one in mind that i think coupd be better- each parent returns it’s “transform” to its children (something like _computeSchematicTransform), this is better than offsetting in a later render phase.

I can give it a try shortly, feel free to take a stab!

2024-12-17 20:16 UTC, seveibar commented
Basically _computeSchematicPositionBeforeLayout should return the correct schematic position for children (offset by all parent groups)

2024-12-21 20:46 UTC, imrishabh18 commented
@seveibar This is what you mean't by having another function to compute the offset for the decedent's?

2024-12-21 20:49 UTC, seveibar requested changes

2024-12-21 20:49 UTC, seveibar commented on lib/components/primitive-components/Group/Group.ts
> +    const { db } = this.root!
This method shouldnt mutate, never mutate db unless you're definitely inside a render phase and the name of the method makes sense to mutate

2024-12-21 20:53 UTC, seveibar commented
@imrishabh18 i'll record a video for you

2024-12-21 21:47 UTC, closed without merging