add 4pin crystal
tscircuit/core pull request #440
Opened 2024-12-20 06:52 UTC by techmannih

4pinCrystal
/claim #389

2024-12-20 07:52 UTC, imrishabh18 commented on lib/components/normal-components/Crystal_4Pin.ts
> +        pin4: ["cap2", "bottom_right"],
The alias for this probably should be `top`, `bottom`, `left` and `right`, according to the symbol image

2024-12-20 07:52 UTC, imrishabh18 commented on lib/components/normal-components/Crystal_4Pin.ts
I think probably we should use the `<Crystal />` component already present, and not introduce a new component just for when we are having 4pins?

cc: @seveibar

2024-12-22 03:53 UTC, seveibar commented on lib/components/normal-components/Crystal_4Pin.ts
yes

2024-12-22 03:53 UTC, seveibar requested changes
see rishabh's comment

2024-12-24 17:54 UTC, imrishabh18 commented
@techmannih Please address the comments before asking for the review's

2024-12-24 18:07 UTC, seveibar commented on lib/components/normal-components/Crystal_4Pin.ts
No modify the existing Crystal to support the pinVariant prop

2024-12-25 02:19 UTC, closed without merging