feat: pcb_keepout added
tscircuit/core pull request #48
Opened 2024-09-06 18:10 UTC by imrishabh18

2024-09-06 19:04 UTC, seveibar commented on lib/components/primitive-components/Keepout.ts
> +        },
the rect vs circle should not have their centers defined differently, we should fix this in soup before encoding it into core

2024-09-06 19:06 UTC, seveibar commented on lib/components/primitive-components/Keepout.ts
> +        },
https://github.com/tscircuit/circuit-json/issues/40

2024-09-06 19:08 UTC, seveibar requested changes
looks good, but we should resolve the soup definition issues. IMO it is always worth having API repos like @tscircuit/soup and @tscircuit/props PRs reviewed because as soon as we realize something is wrong in the api design we generally shouldn't merge anything that uses the the deprecated api design

2024-09-06 19:10 UTC, seveibar commented on lib/components/primitive-components/Keepout.ts
> +export class KeepOut extends PrimitiveComponent<typeof pcbKeepoutProps> {
(this is the google convention vs the microsoft convention for camelCase)

2024-09-06 20:20 UTC, imrishabh18 commented
@seveibar For keepout the layer value can be both `top` and `bottom`, right?

2024-09-07 16:00 UTC, seveibar approved these changes

2024-09-08 11:35 UTC, merged